[theme]
base="light"
primaryColor="#A100FF"           # Accenture Purple for interactive elements (buttons, sliders, etc.)
backgroundColor="#FFFFFF"         # Pure White for the main background
secondaryBackgroundColor="#F0F2F6" # A very light grey for sidebar and most widgets
textColor="#000000"               # Black for most text
font="sans serif"                 # A clean, modern font

